import { IsString, IsNotEmpty, MaxLength } from 'class-validator';

/**
 * DTO for creating a new Task
 * AI Integration: Generated by ChatGPT
 */
export class CreateTaskDto {
  @IsString()
  @IsNotEmpty()
  @MaxLength(255)
  title!: string;
} 