import {
  IsString,
  IsOptional,
  MaxLength,
  IsBoolean,
  IsArray,
  ArrayUnique,
} from 'class-validator';

/**
 * DTO for updating a Task
 * AI Integration: Generated by ChatGPT
 */
export class UpdateTaskDto {
  @IsOptional()
  @IsString()
  @MaxLength(255)
  title?: string;

  @IsOptional()
  @IsBoolean()
  completed?: boolean;

  @IsOptional()
  @IsArray()
  @ArrayUnique()
  @IsString({ each: true })
  tags?: string[];
} 