<script setup lang="ts">
import { ref } from 'vue'

interface Task {
  id: number
  title: string
  completed: boolean
  createdAt: string
}

const tasks = ref<Task[]>([
  { id: 1, title: 'First Task', completed: false, createdAt: new Date().toISOString() },
  { id: 2, title: 'Second Task', completed: true, createdAt: new Date().toISOString() },
])

const newTaskTitle = ref('')

function addTask() {
  if (!newTaskTitle.value.trim()) return
  tasks.value.push({
    id: Date.now(),
    title: newTaskTitle.value,
    completed: false,
    createdAt: new Date().toISOString(),
  })
  newTaskTitle.value = ''
}

function toggleTask(id: number) {
  const task = tasks.value.find(t => t.id === id)
  if (task) task.completed = !task.completed
}
</script>

<template>
  <div class="min-h-screen bg-gray-100 flex flex-col">
    <header class="bg-white shadow p-4 flex items-center justify-center">
      <span class="text-2xl font-extrabold tracking-tight text-blue-600 drop-shadow-sm select-none">Transformer.AI</span>
      <span class="ml-2 text-xl font-semibold text-gray-800 select-none">Task Manager</span>
    </header>
    <main class="flex-1 flex flex-col px-2 py-4 sm:px-8 sm:py-8">
      <form @submit.prevent="addTask" class="flex flex-col sm:flex-row gap-2 sm:gap-0 mb-6">
        <input
          v-model="newTaskTitle"
          type="text"
          placeholder="Add a new task..."
          class="flex-1 border rounded px-3 py-2 focus:outline-none focus:ring-2 focus:ring-blue-400"
        />
        <button
          type="submit"
          class="bg-blue-500 text-white px-4 py-2 rounded hover:bg-blue-600 transition sm:rounded-l-none sm:rounded-r"
        >
          Add
        </button>
      </form>
      <ul class="flex-1 overflow-y-auto">
        <li
          v-for="task in tasks"
          :key="task.id"
          class="flex flex-col sm:flex-row sm:items-center justify-between py-2 border-b last:border-b-0 gap-1 sm:gap-0"
        >
          <label class="flex items-center gap-2 cursor-pointer">
            <input type="checkbox" v-model="task.completed" />
            <span :class="task.completed ? 'line-through text-gray-400' : 'text-gray-900'">{{ task.title }}</span>
          </label>
          <span class="text-xs text-gray-400 sm:text-right">{{ new Date(task.createdAt).toLocaleString() }}</span>
        </li>
      </ul>
    </main>
    <footer class="p-4 text-gray-400 text-xs text-center">AI Integration: UI generated by ChatGPT</footer>
  </div>
</template>

<style scoped>
</style>
