<script setup lang="ts">
import { ref } from 'vue'

interface Task {
  id: number
  title: string
  completed: boolean
  createdAt: string
}

const tasks = ref<Task[]>([
  { id: 1, title: 'First Task', completed: false, createdAt: new Date().toISOString() },
  { id: 2, title: 'Second Task', completed: true, createdAt: new Date().toISOString() },
])

const newTaskTitle = ref('')

function addTask() {
  if (!newTaskTitle.value.trim()) return
  tasks.value.push({
    id: Date.now(),
    title: newTaskTitle.value,
    completed: false,
    createdAt: new Date().toISOString(),
  })
  newTaskTitle.value = ''
}

function toggleTask(id: number) {
  const task = tasks.value.find(t => t.id === id)
  if (task) task.completed = !task.completed
}
</script>

<template>
  <div class="min-h-screen bg-gray-100 flex flex-col items-center py-10">
    <div class="w-full max-w-md bg-white rounded-lg shadow p-6">
      <h1 class="text-2xl font-bold mb-4 text-center">Task Manager</h1>
      <form @submit.prevent="addTask" class="flex mb-4">
        <input
          v-model="newTaskTitle"
          type="text"
          placeholder="Add a new task..."
          class="flex-1 border rounded-l px-3 py-2 focus:outline-none focus:ring-2 focus:ring-blue-400"
        />
        <button
          type="submit"
          class="bg-blue-500 text-white px-4 py-2 rounded-r hover:bg-blue-600 transition"
        >
          Add
        </button>
      </form>
      <ul>
        <li
          v-for="task in tasks"
          :key="task.id"
          class="flex items-center justify-between py-2 border-b last:border-b-0"
        >
          <label class="flex items-center gap-2 cursor-pointer">
            <input type="checkbox" v-model="task.completed" />
            <span :class="task.completed ? 'line-through text-gray-400' : 'text-gray-900'">{{ task.title }}</span>
          </label>
          <span class="text-xs text-gray-400">{{ new Date(task.createdAt).toLocaleString() }}</span>
        </li>
      </ul>
    </div>
    <p class="mt-8 text-gray-400 text-xs">AI Integration: UI generated by ChatGPT</p>
  </div>
</template>

<style scoped>
</style>
